[package]
name = "sp_audio"
version = "0.0.0"
edition = "2021"

[dependencies]
glam = { version = "0.26.0" }
indexmap = { version = "1.9.1" }
log = "0.4.14"
fyrox-sound = "0.28.0"

sp_asset = { path = "../sp_asset", version = "0.0.0" }
sp_sound = { path = "../sp_sound", version = "0.0.0" }
