[package]
name = "sp_input"
version = "0.0.0"
edition = "2021"

[dependencies]
glam = { version = "0.26.0" }
indexmap = { version = "1.9.1" }
bitflags = "1.3.2"
serde = { version = "1.0.136" }
serde_derive = { version = "1.0.136" }
log = "0.4.14"
